global:
  scrape_interval: 10s
  external_labels:
    monitor: "cont-app-monitor"

# end point de metricas por defecto '/metrics'
scrape_configs:
  - job_name: metricas_contenedor_docker
    static_configs:
      - targets: ["host.docker.internal:9323"] 

  - job_name: "metricas_app_python"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app:5000"]
