global:
  scrape_interval: 10s
  external_labels:
    monitor: "cont-app-monitor"

# end point de metricas por defecto '/metrics'
scrape_configs:
  
  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]
  
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
      